name: main
on:
  push:
    branches: [main]

jobs:
  reuse-run:
    uses: ./.github/workflows/reuse.yaml

  another-run:
    uses: ./.github/workflows/reuse.yaml

  run:
    runs-on: ubuntu-latest
    steps:
      - name: print GITHUB RUN_ID
        run: echo "$GITHUB_RUN_ID"
